# .github/workflows/test.yml

name: test
on: 
  push:
  pull_request:
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
      - run: sudo apt-get update && sudo apt-get install -y zsh
      - run: npm ci
      - run: npm test
      - run: npm run check:security
      - run: npm run check-bundle.mjs
